title: Wellcome to HungPT's blog
email: hungpt169@gmai.com
description_en: >-
  My blog is where you find articles about technology mainly related to AI and machine
  learning, as well as an articles about lifestyle of an AI engineer in Tokyo
description_jp: >-
  本ブログはテクノロジー（主にAIと機械学習関連）についての記事を掲載します。それに加えて、私の日常生活について
  の記事もたまに書くので、東京エンジニアのライフスタイルについて興味があれば、ぜひ見てみてください。
description_vi: >-
  Blog của tôi là nơi bạn có thể tìm thấy những bài viết về công nghệ chủ yếu liên quan
  tới AI và machine learning, bên cạnh đó bạn cũng có thể bắt gặp những bài viết về cuộc
  sống hàng ngày của tôi như một kỹ sư AI ở Tokyo
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  truythu169

# Build settings
markdown: kramdown
theme: jekyll-theme-cayman
plugins:
  - jekyll-feed
